services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - SPOTIFY_REDIRECT_URI=http://127.0.0.1:3001/api/auth/spotify/callback
      - FRONTEND_URL=http://127.0.0.1:3000
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/api/health']
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://127.0.0.1:3001/api}
        - VITE_AUTH_BASE_URL=${VITE_AUTH_BASE_URL:-http://127.0.0.1:3001/api}
        - VITE_APP_NAME=${VITE_APP_NAME:-FlipSide Player}
    ports:
      - '3000:80'
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
